#!/bin/bash
#SBATCH --account ibms
#SBATCH --partition=ada
#SBATCH --time=10:00:00
#SBATCH --nodes=1 --ntasks=4
#SBATCH --job-name="FastQC"
#SBATCH --mail-user=amsha.ramburan@uct.ac.za
#SBATCH --mail-type=ALL

# Load FastQC module
module load software/FastQC-0.12.1

# Define directories
input_dir="/scratch/01456151/rawdata/"
output_dir="/scratch/01456151/fastqc/"

# List of unzipped files. Format: filename_1.fq and filename_2.fq)
files=(
15390_17_1.fq 18258_17_1.fq 29665_17_1.fq 3286_17_1.fq
15390_17_2.fq 18258_17_2.fq 29665_17_2.fq 3286_17_2.fq
)

# Loop through each and run FastQC
for filename in "${files[@]}"; do
file_path="${input_dir}${filename}"

if [ -e "$file_path" ]; then
fastqc "$file_path" -o "$output_dir"
else
echo "File not found: $file_path"
fi
done
